# Corresponding local checkpoint: guacamol/gvae-v4-recon15.056-kld28.455-tot26.415-fcd2.3818-e84_3ycztv0j (260417-000214).pth
exp_name: guacamol_gvae_rsg_tfenc
seed: 123

wandb:
  project: HGR-gvae-tfenc

data:
  name: guacamol
  max_vol: 175
  padding_idx: -1

gvae:
  type: GVAE
  latent_dim: 768
  max_vol: 175
  bs: 256
  padding_idx: -1
  rule_embed_dim: 768
  start_rule_embedding: false
  use_nt_conditioning: true
  dropout: 0.1
  rule_init:
    mode: hybrid_struct
    wl_iterations: 3
    freeze_feature_bank: true
  encoder_params:
    name: Transformer
    hidden_dim: 384
    num_layers: 7
    num_heads: 8
    ff_mult: 1
    bidirectional: false
  decoder_params:
    name: GRU
    hidden_dim: 1024
    num_layers: 3

train:
  n_iters: 200
  beta: 0.5
  anneal_steps: 300
  fix_steps: 500
  earlystopping:
    start: 10
    patience: 8
  optimizer: adamw
  lr: 0.00012662048420548623
  lr_decay: 1.0
  weight_decay: 0.001296195155651693
  warmup: 4000
  grad_clip: 1.0
  eps: 1e-8

eval:
  decode_batch_size: 128

grammar:
  type: "RSG"
  vocab_len: 1000

path:
  raw_data:
    train: 'raw/new_train.smiles'
    test: 'raw/new_test.smiles'
  vocab_path: "ringdiv300k_vocab_1000.txt"
  grammar_path: "RSG2385_guacamol.pklz"
  gvae_ckpt_path: null
