exp_name: ringdiv300k_diff_rsg_dit_tfenc
seed: 123

data:
  name: ringdiv300k
  max_vol: 137
  padding_idx: -1

train:
  num_epochs: 300
  earlystopping:
    start: 6
    patience: 8
  bs: 1024
  snapshot_freq: 1
  snapshot_sampling: True
  optimizer: adamw
  reduce_mean: False
  lr: 0.0007547697270760524
  lr_decay: 0.999
  weight_decay: 4.2341097440045295e-6
  warmup: 1000
  grad_clip: 2.0
  ema_decay: 0.999
  eps: 1e-8

scorenet:
  type: ScoreDiT
  latent_dim: 256
  hidden_dim: 512
  dropout: 0.05
  input_layer_norm: true
  use_skip_proj: true
  num_layers: 8
  num_heads: 8
  seq_len: 16
  ff_mult: 4
  time_cond_dim: 512

sde:
  type: VPSDE
  num_scales: 1000
  schedule: linear
  beta_min: 0.06083730653644787
  beta_max: 28.234471955037492

sample:
  method: pc
  predictor: Euler
  corrector: None
  probability_flow: False
  noise_removal: True
  n_steps: 2
  snr: 0.1
  scale_eps: 0.1

eval:
  batch_size: 1024
  num_samples: 1000
  workers: 24
  metrics: ringdiv300k

path:
  vocab_len: 1000
  vocab_path: ringdiv300k_vocab_1000.txt
  grammar_path: RSG6205_ringdiv300k.pklz
  gvae_ckpt_use_manifest: false
  gvae_ckpt_path: "ringdiv300k/gvae-RSG-recon31.196-kld29.270-tot39.888-fcd1.6654-e44_izasbanw (260416-051638).pth"
  latent_cache_mode: mu
  latent_preprocess: standardize
  latent_preprocess_eps: 1.0e-6
  latent_cache_version: v2
  scorenet_ckpt_path: "ringdiv300k/ScoreNet-ns0.00147-fcd1.5025-val1.0000(260416-132348-52).pt"
